# Generated by Django 5.1.4 on 2025-01-16 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('start', '0003_alter_person_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=78)),
                ('day', models.DateField()),
                ('time', models.DateTimeField()),
                ('color', models.CharField(max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.person')),
            ],
        ),
    ]
