# Generated by Django 5.1.4 on 2025-01-28 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('start', '0003_alter_person_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=71)),
                ('url_Text', models.CharField(blank=True, max_length=300, null=True)),
                ('url_title', models.CharField(blank=True, max_length=100, null=True)),
                ('url_subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='start.person')),
            ],
        ),
    ]
