# Generated by Django 5.1.4 on 2025-02-01 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='url',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anonymity', models.BooleanField()),
                ('text', models.CharField(max_length=3000)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('url_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='focus.url')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reaction', models.IntegerField()),
                ('user_id', models.CharField(max_length=50)),
                ('url_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='focus.text')),
            ],
        ),
        migrations.DeleteModel(
            name='TXT',
        ),
    ]
