# Generated by Django 5.1.4 on 2025-02-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0002_rename_user_url_user_id_alter_url_id_text_likes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='user_id',
            new_name='user',
        ),
    ]
