# Generated by Django 5.1.4 on 2025-02-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0004_rename_url_id_text_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='comments',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
