# Generated by Django 5.1.4 on 2025-02-08 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0006_comment_like_delete_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
    ]
